apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdBackupSchedule
metadata:
  name: etcdbackupschedule-sample
spec:
  schedule: "* * * * *"
  backupTemplate:
    source:
      clusterURL: http://my-cluster:2379
    destination:
      objectURLTemplate: "s3://etcd-operator-backup-test/snapshot-{{ .UID }}.db?region=us-west-2"