apiVersion: etcd.improbable.io/v1alpha1
kind: EtcdBackup
metadata:
  name: etcdbackup-sample
spec:
  source:
    clusterURL: http://my-cluster:2379
  destination:
    objectURLTemplate: "s3://bucketname/snapshot.db?endpoint=http://127.0.0.1:9000&disableSSL=true&s3ForcePathStyle=true&region=eu-west-2"
