apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "etcd-cluster-operator.fullname" . }}-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd-cluster-operator.labels" . | nindent 4 }}
    control-plane: proxy
spec:
  selector:
    matchLabels:
      control-plane: proxy
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: proxy
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: proxy
        args:
          # - --api-port=8080
        image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
      terminationGracePeriodSeconds: 10
