name: Release Docker images
on:
  push:
    branches:
      - 'master'
    tags:
      - "*"
  workflow_call:
  pull_request:
    branches:
      - 'master'
jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          # Need all the history for git describe --tags to work
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.3'
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        run: make docker-build docker-push DOCKER_REPO=lacwork/$GITHUB_REPOSITORY
      


