name: Release Docker images
on:
  push:
    branches:
      - 'master'
    tags:
      - "*"
  workflow_call:
  pull_request:
    branches:
      - 'master'
jobs:
  e2e:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        run: |
          sudo rm -rf /usr/local/go
          curl -sSL "https://dl.google.com/go/go1.14.linux-amd64.tar.gz" -o /tmp/go.tar.gz
          echo "08df79b46b0adf498ea9f320a0f23d6ec59e9003660b4c9c1ce8e5e2c6f823ca  /tmp/go.tar.gz" | sha256sum -c
          sudo tar -xzf /tmp/go.tar.gz -C /usr/local/
          echo "export PATH=$PATH:/usr/local/go/bin"
          echo 'export GOPATH=$HOME/go'
          # Download & verify kubectl
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubectl
          echo "3ff48e12f9c768ad548e4221d805281ea28dfcda5c18b3cd1797fe37aee3012e  kubectl" | sha256sum -c
          # Mark it executable & move to /bin
          sudo chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin
          curl -L -o /tmp/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.5.4/kustomize_v3.5.4_linux_amd64.tar.gz
          echo "5cdeb2af81090ad428e3a94b39779b3e477e2bc946be1fe28714d1ca28502f6a  /tmp/kustomize.tar.gz" | sha256sum -c
          sudo tar -C /usr/local/bin -x -f /tmp/kustomize.tar.gz
      - name: checkout
        uses: actions/checkout@v2
        run: make e2e-kind TEST_PARALLEL_E2E=1 E2E_ARTIFACTS_DIRECTORY=/tmp/etcd-e2e




#
#  test-build-and-push:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          # Need all the history for git describe --tags to work
#          fetch-depth: 0
#      - uses: actions/setup-go@v2
#        with:
#          go-version: '^1.14.3'
#      - name: Unit tests
#        run: make test


#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#      - name: Build and push Docker image
#        run: make docker-build docker-push



